### ISSUE TITLE
Send data via post

### ISSUE THREAD

**Issue by joserract89** [akveo/blur-admin#159]
Hello,

First of all, thanks for your work, it really look awesome.

I would like to know how send data to a NodeJS server using the post method. I've seen that you use UI-Router. I've been investigating and I couldn't find anything of how to send data to a server. I used the method $http.post before, but it doesn't seem to be working here.

Thanks in advance

**Comment by wandri** [comment]
Do you have some error message? 404? 500? in your Browser? I don't think the problem is linked to BlurAdmin.
Because: 
```
function myController ($http){
$http.post(yourApi, yourObject)
}
```
that's working.

**Comment by joserract89** [comment]
Hi wandri, thanks for your response.
I get the error message 500. I've been investigating and I think my error is in the server code. this is my current code (I'm using express):
`var app = require('express')();
port=3000;
app.post('/users', function (req, res) {
  console.log("It works!");
});
app.listen(port, function(){
  var url = 'http://localhost'  + port + '/';
  console.log('Running at ' + url);
});
`
But this code gives an error: it says that the port is already in use. And when I use any other port, it gives the error 500. Where should the code go? It's express necessary?

**Comment by wandri** [comment]
Yes 500 means that's coming from your server. But where is your server?
Have you 2 local apps?
Why are you using the Dasbhoard? Is it to control/check Datas from an another WebApp?
If the answer is YES: 
- Why do you not just connect this app to your webAppAPI? You can install an login service to secure the dashboard.

**Comment by joserract89** [comment]
The server is in my local machine right now because I'm using it for test. I just have one app, and the idea is to create a webpage with role-based authentication, but my idea is that everything is in the same app. Should I have to create another app to store the information in the tables? I would like to have all the tables from the database in the same app.

**Comment by wandri** [comment]
This is what I have done:
- I have an Angular-fullstack webApp (https://github.com/angular-fullstack/generator-angular-fullstack). All is generated (Server, role-based authentication). This is realy great.
- I have an another App (BlurAdmin) for the admin. I get all the data that I need from my angularFullstack API. And this App is protected with tocken system and login access (from the API one more time).

I don't recommand you the Dashboard as your main App, this will be to heavy to load and unnecessary.

I think that you can close the issue because the is not related to an blurAdmin issue.
If you want more information, here is my mail: wghophop@gmail.com

**Comment by joserract89** [comment]
I will take a look to the Angular-fullstack generator. Again, thank you very much for your help!
