### ISSUE TITLE
Cannot transition to abstract state

### ISSUE THREAD

**Issue by trinvh2** [akveo/blur-admin#183]
Hi, first thank for awesome open source theme.

I want to move components.mail into root menu. Like this:
- Dashboard
- Mail
- Components
  ....

However it not works. It throws `Cannot transition to abstract state 'mail'`

How do i can solve this. Any help will be appreciated. Thanks

**Comment by vazh** [comment]
@trinvh2 
this is ui-router expected behaviour when someone trying to transition into abstract state.
i suggest you read ui-router documentation so that you can understand the behaviour of ui-router state.
since it will be more useful if you learn about it rather than us telling you how to do it.

try reading about ui-router nested state

**Comment by ESadouski** [comment]
Please ensure you have completed the following steps:
1. Rewrite all component properties from 'components.mail' to 'mail'
2. Remove 'components.mail' module from the 'components.module.js' and add module 'mail' to the 'pages.module.js'
3. Delete property 'abstract: true' from the 'mail.module.js'
