### ISSUE TITLE
DOM elements inside baPanel not rendered before angular.js controller is executed

### ISSUE THREAD

**Issue by aju9316** [akveo/blur-admin#194]
I have a some elements inside baPanel div and when i try to select the element through document.getElementById('someElement') it returns null. If i remove baPanel directive, it works fine.

Also, if i move the document.getElementById('someElement') code inside a default setTimeout function it will work properly.

NOTE: I am doing document.getElementById('someElement') inside its respective angular controller.

**Comment by ESadouski** [comment]
@aju9316 We think your problem is that you want to get element until transclusion is executed. Please look at http://odetocode.com/blogs/scott/archive/2014/05/28/compile-pre-and-post-linking-in-angularjs.aspx
Also we think that the DOM manipulations are not the Angular way. Here's a good article to better understand the Angular philosophy: http://stackoverflow.com/questions/14994391/
