### ISSUE TITLE
this is a silly question

### ISSUE THREAD

**Issue by sunnyzhang66** [akveo/blur-admin#197]
Hi 
I am new to angular , you did great job for angular template , I love it!

This is very silly question  : what is "::" mean , something like  {{ ::message.author }} ?

Thanks
Sunny

**Comment by Leftyx** [comment]
That is [One-time binding](https://docs.angularjs.org/guide/expression#one-time-binding).

> An expression that starts with :: is considered a one-time expression. One-time expressions will stop recalculating once they are stable, which happens after the first digest if the expression result is a non-undefined value (see value stabilization algorithm below).

**Comment by PhiLhoSoft** [comment]
@sunnyzhang66 This is relatively new in the AngularJS world, that's why lot of tutorials don't mention it...
Suggestion: try and make more expressive subjects, like "What is this double-colon notation" or similar. Useful here (for searches, etc.) and everywhere on the Internet... (forums, etc.).
Other suggestion: close this issue if you think it is answered, to keep the list "clean". 😄

**Comment by sunnyzhang66** [comment]
thank you very much for the details and suggestions!!!
