### ISSUE TITLE
how to use it with jsp ?

### ISSUE THREAD

**Issue by youussef** [akveo/blur-admin#31]
hello
thank you for this really awesome template
i tried to work with this template with Jsp but unfortunately it doesn't work 
![screen shot 2016-05-16 at 9 36 34 am](https://cloud.githubusercontent.com/assets/16546837/15284613/3d241334-1b4a-11e6-9046-f48f2dc7eb4b.png)
can you please tell me how or why it doesn't work 
based on the demo i saw i really like this template 
thank you a lot

**Comment by MEKDAD3** [comment]
hiii , if you have built the template please send me the release , i can't build it and i really need it.

**Comment by youussef** [comment]
dude the template does not work

**Comment by lugovsky** [comment]
@youussef It works, look at the demo. We have built it yesterday from master branch. Installation guidelines can be found here: http://akveo.github.io/blur-admin/articles/002-installation-guidelines/. Please follow the guideline attentively.

Information you provided is not enough to detect the problem. Probably you didn't include appropriate CSS file in your page.

Anyway this problem is 100% not related to our template, it's related to the way you integrated it. Closing issue

**Comment by youussef** [comment]
i did all of the steps but it doesn't work :(

**Comment by alpamys-qanybet** [comment]
@youussef, ``SPA`` stands for ``SinglePageApplication``. If you use ``jsp`` then it is ``JavaServerPages``. Are you sure you want to use it inside ``JSP``? I use ``SPA`` inside ``Java`` and ``php`` projects as rest approach. NOT as template for my php or jsp pages.

**Comment by youussef** [comment]
@alpamys-qanybet this was 2 years ago 😑

**Comment by alpamys-qanybet** [comment]
@youussef, anyway. Good luck
